In [2]:
import pandas as pd

In [3]:
raw_data_fp = "../data/raw"
sales_train_validation = pd.read_csv(f"{raw_data_fp}/sales_train_validation.csv")
calendar = pd.read_csv(f"{raw_data_fp}/calendar.csv")
sell_prices = pd.read_csv(f"{raw_data_fp}/sell_prices.csv")

# 1) sales_train_validation

#### a) What does one row represent?
One row represents the historical daily unit sales per product and store _[(Kaggle)](https://www.kaggle.com/competitions/m5-forecasting-accuracy/data)_

In [4]:
sales_train_validation.shape

(30490, 1919)

In [5]:
sales_train_validation.head()

,id,item_id,dept_id,cat_id,store_id,state_id,d_1,d_2,d_3,d_4,...,d_1904,d_1905,d_1906,d_1907,d_1908,d_1909,d_1910,d_1911,d_1912,d_1913
0,HOBBIES_1_001_CA_1_validation,HOBBIES_1_001,HOBBIES_1,HOBBIES,CA_1,CA,0,0,0,0,...,1,3,0,1,1,1,3,0,1,1
1,HOBBIES_1_002_CA_1_validation,HOBBIES_1_002,HOBBIES_1,HOBBIES,CA_1,CA,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0
2,HOBBIES_1_003_CA_1_validation,HOBBIES_1_003,HOBBIES_1,HOBBIES,CA_1,CA,0,0,0,0,...,2,1,2,1,1,1,0,1,1,1
3,HOBBIES_1_004_CA_1_validation,HOBBIES_1_004,HOBBIES_1,HOBBIES,CA_1,CA,0,0,0,0,...,1,0,5,4,1,0,1,3,7,2
4,HOBBIES_1_005_CA_1_validation,HOBBIES_1_005,HOBBIES_1,HOBBIES,CA_1,CA,0,0,0,0,...,2,1,1,0,1,1,2,2,2,4

In [6]:
sales_train_validation.nunique()

id          30490
item_id      3049
dept_id         7
cat_id          3
store_id       10
            ...
d_1909         53
d_1910         57
d_1911         61
d_1912         73
d_1913         65
Length: 1919, dtype: int64

In [7]:
for col in sales_train_validation.columns[:6]:
    print(col)
    print(sales_train_validation[col].nunique())
    print(sales_train_validation[col].unique(), '\n\n')

# sales_train_validation['cat_id'].unique()

id
30490
['HOBBIES_1_001_CA_1_validation' 'HOBBIES_1_002_CA_1_validation'
 'HOBBIES_1_003_CA_1_validation' ... 'FOODS_3_825_WI_3_validation'
 'FOODS_3_826_WI_3_validation' 'FOODS_3_827_WI_3_validation']


item_id
3049
['HOBBIES_1_001' 'HOBBIES_1_002' 'HOBBIES_1_003' ... 'FOODS_3_825'
 'FOODS_3_826' 'FOODS_3_827']


dept_id
7
['HOBBIES_1' 'HOBBIES_2' 'HOUSEHOLD_1' 'HOUSEHOLD_2' 'FOODS_1' 'FOODS_2'
 'FOODS_3']


cat_id
3
['HOBBIES' 'HOUSEHOLD' 'FOODS']


store_id
10
['CA_1' 'CA_2' 'CA_3' 'CA_4' 'TX_1' 'TX_2' 'TX_3' 'WI_1' 'WI_2' 'WI_3']


state_id
3
['CA' 'TX' 'WI']

#### b) What is the purpose of this table?
The purpose of this table is to provide the daily historical unit sales for each product-store combination, which serves as the basis for forecasting future demand

#### c) What are the important columns? (Don't explain every column individually.)
The important columns are going to include the store IDs, which intrinsically give us the state as well. Each store will have a different consumer base and may have different demand trends for different categories or items. Additionally, dept_id will give us both the category and information on whatever the further split down is - which I don't know at this time. Lastly, all of the d_xxxx columns will be roughly equally relevant since that's the actual sales data upon which our forecasting models will be trained. More recent data will likely contain more pertinent information, but retail sales can be highly seasonal, so given that we have over 5 years of data, the data points corresponding to any columns 365 days before will likely have an impact on that column.

In [8]:
1913 / 365

5.241095890410959

#### d) Are there any columns you don't understand yet?
As I mentioned in the last question, I don't know whether the dept_id split of the categories has any material meaning, or if it's arbitrary just based on the number of products. Otherwise, the information is relatively self-explanatory.

# 2) Calendar

In [9]:
calendar.shape

(1969, 14)

In [10]:
calendar.head()

,date,wm_yr_wk,weekday,wday,month,year,d,event_name_1,event_type_1,event_name_2,event_type_2,snap_CA,snap_TX,snap_WI
0,2011-01-29,11101,Saturday,1,1,2011,d_1,NaN,NaN,NaN,NaN,0,0,0
1,2011-01-30,11101,Sunday,2,1,2011,d_2,NaN,NaN,NaN,NaN,0,0,0
2,2011-01-31,11101,Monday,3,1,2011,d_3,NaN,NaN,NaN,NaN,0,0,0
3,2011-02-01,11101,Tuesday,4,2,2011,d_4,NaN,NaN,NaN,NaN,1,1,0
4,2011-02-02,11101,Wednesday,5,2,2011,d_5,NaN,NaN,NaN,NaN,1,0,1

In [16]:
calendar.tail()

,date,wm_yr_wk,weekday,wday,month,year,d,event_name_1,event_type_1,event_name_2,event_type_2,snap_CA,snap_TX,snap_WI
1964,2016-06-15,11620,Wednesday,5,6,2016,d_1965,NaN,NaN,NaN,NaN,0,1,1
1965,2016-06-16,11620,Thursday,6,6,2016,d_1966,NaN,NaN,NaN,NaN,0,0,0
1966,2016-06-17,11620,Friday,7,6,2016,d_1967,NaN,NaN,NaN,NaN,0,0,0
1967,2016-06-18,11621,Saturday,1,6,2016,d_1968,NaN,NaN,NaN,NaN,0,0,0
1968,2016-06-19,11621,Sunday,2,6,2016,d_1969,NBAFinalsEnd,Sporting,Father's day,Cultural,0,0,0

In [18]:
calendar.iloc[356:370]

,date,wm_yr_wk,weekday,wday,month,year,d,event_name_1,event_type_1,event_name_2,event_type_2,snap_CA,snap_TX,snap_WI
356,2012-01-20,11151,Friday,7,1,2012,d_357,NaN,NaN,NaN,NaN,0,0,0
357,2012-01-21,11152,Saturday,1,1,2012,d_358,NaN,NaN,NaN,NaN,0,0,0
358,2012-01-22,11152,Sunday,2,1,2012,d_359,NaN,NaN,NaN,NaN,0,0,0
359,2012-01-23,11152,Monday,3,1,2012,d_360,NaN,NaN,NaN,NaN,0,0,0
360,2012-01-24,11152,Tuesday,4,1,2012,d_361,NaN,NaN,NaN,NaN,0,0,0
361,2012-01-25,11152,Wednesday,5,1,2012,d_362,NaN,NaN,NaN,NaN,0,0,0
362,2012-01-26,11152,Thursday,6,1,2012,d_363,NaN,NaN,NaN,NaN,0,0,0
363,2012-01-27,11152,Friday,7,1,2012,d_364,NaN,NaN,NaN,NaN,0,0,0
364,2012-01-28,11201,Saturday,1,1,2012,d_365,NaN,NaN,NaN,NaN,0,0,0
365,2012-01-29,11201,Sunday,2,1,2012,d_366,NaN,NaN,NaN,NaN,0,0,0
366,2012-01-30,11201,Monday,3,1,2012,d_367,NaN,NaN,NaN,NaN,0,0,0
367,2012-01-31,11201,Tuesday,4,1,2012,d_368,NaN,NaN,NaN,NaN,0,0,0
368,2012-02-01,11201,Wednesday,5,2,2012,d_369,NaN,NaN,NaN,NaN,1,1,0
369,2012-02-02,11201,Thursday,6,2,2012,d_370,NaN,NaN,NaN,NaN,1,0,1

In [21]:
for col in calendar.columns[:5]:
    print(col)
    print(calendar[col].nunique())
    if col != "wm_yr_wk":
        print(calendar[col].unique())
    print("\n")

date
1969
['2011-01-29' '2011-01-30' '2011-01-31' ... '2016-06-17' '2016-06-18'
 '2016-06-19']


wm_yr_wk
282


weekday
7
['Saturday' 'Sunday' 'Monday' 'Tuesday' 'Wednesday' 'Thursday' 'Friday']


wday
7
[1 2 3 4 5 6 7]


month
12
[ 1  2  3  4  5  6  7  8  9 10 11 12]

In [ ]:
for col in calendar.columns[5:9]:
    print(col)
    print(calendar[col].nunique())
    if col != "wm_yr_wk":
        print(calendar[col].unique())
    print("\n")

year
6
[2011 2012 2013 2014 2015 2016]


d
1969
['d_1' 'd_2' 'd_3' ... 'd_1967' 'd_1968' 'd_1969']


event_name_1
30
[nan 'SuperBowl' 'ValentinesDay' 'PresidentsDay' 'LentStart' 'LentWeek2'
 'StPatricksDay' 'Purim End' 'OrthodoxEaster' 'Pesach End' 'Cinco De Mayo'
 "Mother's day" 'MemorialDay' 'NBAFinalsStart' 'NBAFinalsEnd'
 "Father's day" 'IndependenceDay' 'Ramadan starts' 'Eid al-Fitr'
 'LaborDay' 'ColumbusDay' 'Halloween' 'EidAlAdha' 'VeteransDay'
 'Thanksgiving' 'Christmas' 'Chanukah End' 'NewYear' 'OrthodoxChristmas'
 'MartinLutherKingDay' 'Easter']


event_type_1
4
[nan 'Sporting' 'Cultural' 'National' 'Religious']

In [25]:
for col in calendar.columns[9:]:
    print(col)
    print(calendar[col].nunique())
    if col != "wm_yr_wk":
        print(calendar[col].unique())
    print("\n")

event_name_2
4
[nan 'Easter' 'Cinco De Mayo' 'OrthodoxEaster' "Father's day"]


event_type_2
2
[nan 'Cultural' 'Religious']


snap_CA
2
[0 1]


snap_TX
2
[0 1]


snap_WI
2
[0 1]

In [26]:
calendar.head()

,date,wm_yr_wk,weekday,wday,month,year,d,event_name_1,event_type_1,event_name_2,event_type_2,snap_CA,snap_TX,snap_WI
0,2011-01-29,11101,Saturday,1,1,2011,d_1,NaN,NaN,NaN,NaN,0,0,0
1,2011-01-30,11101,Sunday,2,1,2011,d_2,NaN,NaN,NaN,NaN,0,0,0
2,2011-01-31,11101,Monday,3,1,2011,d_3,NaN,NaN,NaN,NaN,0,0,0
3,2011-02-01,11101,Tuesday,4,2,2011,d_4,NaN,NaN,NaN,NaN,1,1,0
4,2011-02-02,11101,Wednesday,5,2,2011,d_5,NaN,NaN,NaN,NaN,1,0,1

In [ ]:
calendar[calendar["wm_yr_wk"].astype("str").str.endswith("53")]

,date,wm_yr_wk,weekday,wday,month,year,d,event_name_1,event_type_1,event_name_2,event_type_2,snap_CA,snap_TX,snap_WI
1092,2014-01-25,11353,Saturday,1,1,2014,d_1093,NaN,NaN,NaN,NaN,0,0,0
1093,2014-01-26,11353,Sunday,2,1,2014,d_1094,NaN,NaN,NaN,NaN,0,0,0
1094,2014-01-27,11353,Monday,3,1,2014,d_1095,NaN,NaN,NaN,NaN,0,0,0
1095,2014-01-28,11353,Tuesday,4,1,2014,d_1096,NaN,NaN,NaN,NaN,0,0,0
1096,2014-01-29,11353,Wednesday,5,1,2014,d_1097,NaN,NaN,NaN,NaN,0,0,0
1097,2014-01-30,11353,Thursday,6,1,2014,d_1098,NaN,NaN,NaN,NaN,0,0,0
1098,2014-01-31,11353,Friday,7,1,2014,d_1099,NaN,NaN,NaN,NaN,0,0,0

In [40]:
calendar.iloc[721:740]

,date,wm_yr_wk,weekday,wday,month,year,d,event_name_1,event_type_1,event_name_2,event_type_2,snap_CA,snap_TX,snap_WI
721,2013-01-19,11252,Saturday,1,1,2013,d_722,NaN,NaN,NaN,NaN,0,0,0
722,2013-01-20,11252,Sunday,2,1,2013,d_723,NaN,NaN,NaN,NaN,0,0,0
723,2013-01-21,11252,Monday,3,1,2013,d_724,MartinLutherKingDay,National,NaN,NaN,0,0,0
724,2013-01-22,11252,Tuesday,4,1,2013,d_725,NaN,NaN,NaN,NaN,0,0,0
725,2013-01-23,11252,Wednesday,5,1,2013,d_726,NaN,NaN,NaN,NaN,0,0,0
726,2013-01-24,11252,Thursday,6,1,2013,d_727,NaN,NaN,NaN,NaN,0,0,0
727,2013-01-25,11252,Friday,7,1,2013,d_728,NaN,NaN,NaN,NaN,0,0,0
728,2013-01-26,11301,Saturday,1,1,2013,d_729,NaN,NaN,NaN,NaN,0,0,0
729,2013-01-27,11301,Sunday,2,1,2013,d_730,NaN,NaN,NaN,NaN,0,0,0
730,2013-01-28,11301,Monday,3,1,2013,d_731,NaN,NaN,NaN,NaN,0,0,0
731,2013-01-29,11301,Tuesday,4,1,2013,d_732,NaN,NaN,NaN,NaN,0,0,0
732,2013-01-30,11301,Wednesday,5,1,2013,d_733,NaN,NaN,NaN,NaN,0,0,0
733,2013-01-31,11301,Thursday,6,1,2013,d_734,NaN,NaN,NaN,NaN,0,0,0
734,2013-02-01,11301,Friday,7,2,2013,d_735,NaN,NaN,NaN,NaN,1,1,0
735,2013-02-02,11302,Saturday,1,2,2013,d_736,NaN,NaN,NaN,NaN,1,0,1
736,2013-02-03,11302,Sunday,2,2,2013,d_737,SuperBowl,Sporting,NaN,NaN,1,1,1
737,2013-02-04,11302,Monday,3,2,2013,d_738,NaN,NaN,NaN,NaN,1,0,0
738,2013-02-05,11302,Tuesday,4,2,2013,d_739,NaN,NaN,NaN,NaN,1,1,1
739,2013-02-06,11302,Wednesday,5,2,2013,d_740,NaN,NaN,NaN,NaN,1,1,1

In [35]:
calendar.iloc[1088:1100]

,date,wm_yr_wk,weekday,wday,month,year,d,event_name_1,event_type_1,event_name_2,event_type_2,snap_CA,snap_TX,snap_WI
1088,2014-01-21,11352,Tuesday,4,1,2014,d_1089,NaN,NaN,NaN,NaN,0,0,0
1089,2014-01-22,11352,Wednesday,5,1,2014,d_1090,NaN,NaN,NaN,NaN,0,0,0
1090,2014-01-23,11352,Thursday,6,1,2014,d_1091,NaN,NaN,NaN,NaN,0,0,0
1091,2014-01-24,11352,Friday,7,1,2014,d_1092,NaN,NaN,NaN,NaN,0,0,0
1092,2014-01-25,11353,Saturday,1,1,2014,d_1093,NaN,NaN,NaN,NaN,0,0,0
1093,2014-01-26,11353,Sunday,2,1,2014,d_1094,NaN,NaN,NaN,NaN,0,0,0
1094,2014-01-27,11353,Monday,3,1,2014,d_1095,NaN,NaN,NaN,NaN,0,0,0
1095,2014-01-28,11353,Tuesday,4,1,2014,d_1096,NaN,NaN,NaN,NaN,0,0,0
1096,2014-01-29,11353,Wednesday,5,1,2014,d_1097,NaN,NaN,NaN,NaN,0,0,0
1097,2014-01-30,11353,Thursday,6,1,2014,d_1098,NaN,NaN,NaN,NaN,0,0,0
1098,2014-01-31,11353,Friday,7,1,2014,d_1099,NaN,NaN,NaN,NaN,0,0,0
1099,2014-02-01,11401,Saturday,1,2,2014,d_1100,NaN,NaN,NaN,NaN,1,1,0

In [41]:
calendar["event_type_1"].unique()

array([nan, 'Sporting', 'Cultural', 'National', 'Religious'], dtype=object)

In [42]:
calendar["event_type_2"].unique()

array([nan, 'Cultural', 'Religious'], dtype=object)

In [50]:
# Pattern in snap field?
s = calendar["snap_CA"]

groups = (s != s.shift()).cumsum()
s.groupby(groups).agg(["first", "size"])

         first  size
snap_CA
1            0     3
2            1    10
3            0    18
4            1    10
5            0    21
...        ...   ...
127          0    20
128          1    10
129          0    21
130          1    10
131          0     9

[131 rows x 2 columns]

### Initial Observations

**Relationship between `date`, `d`, and `wm_yr_wk`:**

> `date` is simply the calendar date, starting from 2011-01-29. `d`, is the count of days starting from 2011-01-29 (starting at 1). `wm_yr_wk` is short for "WalMart Year Week". It is formatted xYYWW, where x is always 1 for a currently unknown reason. YY is their retail year, which extends into the following calendar year's January. Then WW is their retail week which typically goes from 01-52, but some years will go from 01-53, depending on where the weekdays land (the cutoff for starting the new year might be whether 1/26 is a Saturday, based on the 2013 and 2014 date encoding patterns).

**Why do all three exist?**

> They all represent different but independently useful ways to represent dates and timeframes.

**Role of `event_name_*` and `event_type_*`:**

> These represent significant holidays/events that may affect consumer activity and sales. The holidays/events are categorized as one of "Sporting", "Cultural", "National", or "Religious".

**Role of `snap_CA`, `snap_TX`, and `snap_WI`:**

> At this time, the exact role of these fields is unclear to me. I can see that they are binary/boolean representations of some common feature for each of the 3 states represented (California, Texas, and Wisconsin), though I don't know exactly what "snap" means.

**Anything else that stands out?**

> Not immediately, though this is simply a table of dates, so it's likely only used as a tool/reference.

#### a) What does one row represent?

Each row represents a single calendar day and the various ways to categorize/group them (by retail year, week, month, etc.)

#### b) What is the purpose of this table?

As a tool/reference to line up sales data with dates, holidays, days of the week, etc. so that patterns may be extracted.

#### c) What are the important columns? (Don't explain every column individually.)

`date` is probably the most important by default. Everything else is just another way to represent the date as far as I can tell.

#### d) Are there any columns you don't understand yet?

Yes - as I mentioned, I don't yet know what the last three "snap" fields represent in this table.

# 3. Sell Prices

In [51]:
sell_prices.shape

(6841121, 4)

In [52]:
sell_prices.head()

  store_id        item_id  wm_yr_wk  sell_price
0     CA_1  HOBBIES_1_001     11325        9.58
1     CA_1  HOBBIES_1_001     11326        9.58
2     CA_1  HOBBIES_1_001     11327        8.26
3     CA_1  HOBBIES_1_001     11328        8.26
4     CA_1  HOBBIES_1_001     11329        8.26

---

#### a) What does one row represent?

> The price at which each specific item was sold at each store during each retail week, with the weeks' encoding corresponding the the `calendar` table

#### b) What is the purpose of this table?

> To show the prices of specific items over time at each location.

#### c) What are the important columns? (Don't explain every column individually.)

> All four are likely going to be essential, since we need to know at what price each product was sold at at each location so we can tie it to the actual sales data. Our end goal of this entire project is to increase revenue and we can't do that without knowing the prices at which we're selling our products.

#### d) Are there any columns you don't understand yet?

> No - this appears to be the most straightforward table of the three


### Initial Observations

**What does one row represent?**

> The price of an product at a store during a particular week (unclear whether this is the price starting on the first day of the week, ending on the last day of the week, or whether they change prices midweek)

**Relationship between `store_id`, `item_id`, and `wm_yr_wk`:**

> Independently, none of these fields are dependent on one another. They basically serve as primary keys for the price for the purposes of this table.

**How often do prices change?**

> Prices are relatively stable. Some products appear to never change price, while others change periodically. I attempted to quantify the number of price changes per product-store combination, but realized this metric may not be directly comparable because different combinations appear to have different lengths of price history.

**Anything surprising?**

> Not immediately

In [53]:
sell_prices.head()

  store_id        item_id  wm_yr_wk  sell_price
0     CA_1  HOBBIES_1_001     11325        9.58
1     CA_1  HOBBIES_1_001     11326        9.58
2     CA_1  HOBBIES_1_001     11327        8.26
3     CA_1  HOBBIES_1_001     11328        8.26
4     CA_1  HOBBIES_1_001     11329        8.26

In [59]:
single_product_test_df = sell_prices[
    ((sell_prices["store_id"] == "CA_1") 
    & (sell_prices["item_id"] == "HOBBIES_1_001"))
]
single_product_test_df

    store_id        item_id  wm_yr_wk  sell_price
0       CA_1  HOBBIES_1_001     11325        9.58
1       CA_1  HOBBIES_1_001     11326        9.58
2       CA_1  HOBBIES_1_001     11327        8.26
3       CA_1  HOBBIES_1_001     11328        8.26
4       CA_1  HOBBIES_1_001     11329        8.26
..       ...            ...       ...         ...
149     CA_1  HOBBIES_1_001     11617        8.38
150     CA_1  HOBBIES_1_001     11618        8.38
151     CA_1  HOBBIES_1_001     11619        8.38
152     CA_1  HOBBIES_1_001     11620        8.38
153     CA_1  HOBBIES_1_001     11621        8.38

[154 rows x 4 columns]

In [ ]:
single_product_test_df[
    single_product_test_df["sell_price"] 
    != single_product_test_df["sell_price"].shift(
        fill_value=single_product_test_df["sell_price"].iloc[0]
    )
]

2

In [69]:
single_product_test_df["sell_price"].unique()

array([9.58, 8.26, 8.38])

In [66]:
sell_prices["item_id"].nunique()

3049

In [67]:
for s, i in zip(sell_prices["store_id"].unique(), sell_prices["item_id"].unique()):
    print(s, i)

CA_1 HOBBIES_1_001
CA_2 HOBBIES_1_002
CA_3 HOBBIES_1_003
CA_4 HOBBIES_1_004
TX_1 HOBBIES_1_005
TX_2 HOBBIES_1_006
TX_3 HOBBIES_1_007
WI_1 HOBBIES_1_008
WI_2 HOBBIES_1_009
WI_3 HOBBIES_1_010

In [ ]:
price_change_df = pd.DataFrame(columns=["store_id", "item_id", "number_of_price_changes"])
for store in sell_prices["store_id"].unique():
    for item in sell_prices["item_id"].unique():
        single_product_test_df = sell_prices[
            ((sell_prices["store_id"] == store) 
            & (sell_prices["item_id"] == item))
        ]
        number_of_price_changes = len(
                single_product_test_df[
                single_product_test_df["sell_price"] 
                != single_product_test_df["sell_price"].shift(
                    fill_value=single_product_test_df["sell_price"].iloc[0]
                )
            ]
        )
        price_change_df.loc[len(price_change_df)] = [store, item, number_of_price_changes]

In [82]:
sell_prices[["store_id", "item_id"]]

        store_id        item_id
0           CA_1  HOBBIES_1_001
1           CA_1  HOBBIES_1_001
2           CA_1  HOBBIES_1_001
3           CA_1  HOBBIES_1_001
4           CA_1  HOBBIES_1_001
...          ...            ...
6841116     WI_3    FOODS_3_827
6841117     WI_3    FOODS_3_827
6841118     WI_3    FOODS_3_827
6841119     WI_3    FOODS_3_827
6841120     WI_3    FOODS_3_827

[6841121 rows x 2 columns]

In [86]:
groups = sell_prices.groupby(["store_id", "item_id"])

In [88]:
for key, group in groups:
    print(key)
    print(group.head())
    break

('CA_1', 'FOODS_1_001')
       store_id      item_id  wm_yr_wk  sell_price
368746     CA_1  FOODS_1_001     11101         2.0
368747     CA_1  FOODS_1_001     11102         2.0
368748     CA_1  FOODS_1_001     11103         2.0
368749     CA_1  FOODS_1_001     11104         2.0
368750     CA_1  FOODS_1_001     11105         2.0

In [91]:
for (store, item), group in groups:
    print(store)
    print(item)
    print(group.head())
    print(type(group))
    break

CA_1
FOODS_1_001
       store_id      item_id  wm_yr_wk  sell_price
368746     CA_1  FOODS_1_001     11101         2.0
368747     CA_1  FOODS_1_001     11102         2.0
368748     CA_1  FOODS_1_001     11103         2.0
368749     CA_1  FOODS_1_001     11104         2.0
368750     CA_1  FOODS_1_001     11105         2.0
<class 'pandas.core.frame.DataFrame'>

In [92]:
data_list = []
for (store, item), group in groups:
    number_of_price_changes = len(
        group[
            group["sell_price"] 
            != group["sell_price"].shift(
                fill_value=group["sell_price"].iloc[0]
            )
        ]
    )
    data_list.append([store, item, number_of_price_changes])

In [93]:
price_change_df = pd.DataFrame(
    columns=["store_id", "item_id", "number_of_price_changes"],
    data=data_list
)

In [95]:
price_change_df.head()

  store_id      item_id  number_of_price_changes
0     CA_1  FOODS_1_001                        1
1     CA_1  FOODS_1_002                        2
2     CA_1  FOODS_1_003                        1
3     CA_1  FOODS_1_004                        3
4     CA_1  FOODS_1_005                        2

In [96]:
group_lengths = []
for (store, item), group in groups:
    group_lengths.append(len(group))

In [97]:
group_lengths

[282,
 282,
 282,
 225,
 282,
 282,
 245,
 225,
 213,
 282,
 256,
 282,
 162,
 280,
 282,
 224,
 282,
 282,
 282,
 174,
 156,
 256,
 282,
 187,
 272,
 191,
 166,
 273,
 281,
 265,
 282,
 210,
 272,
 282,
 282,
 281,
 281,
 206,
 282,
 282,
 156,
 234,
 282,
 282,
 282,
 282,
 244,
 282,
 244,
 161,
 162,
 282,
 282,
 282,
 135,
 175,
 234,
 149,
 110,
 279,
 282,
 282,
 282,
 282,
 282,
 282,
 149,
 282,
 175,
 187,
 273,
 282,
 282,
 282,
 282,
 225,
 175,
 235,
 282,
 256,
 172,
 282,
 282,
 282,
 282,
 256,
 282,
 121,
 281,
 280,
 206,
 256,
 282,
 282,
 282,
 156,
 165,
 170,
 282,
 279,
 282,
 282,
 236,
 282,
 239,
 282,
 206,
 234,
 107,
 282,
 224,
 282,
 151,
 282,
 280,
 162,
 282,
 234,
 277,
 82,
 282,
 278,
 121,
 225,
 282,
 275,
 282,
 282,
 83,
 191,
 282,
 140,
 282,
 282,
 282,
 282,
 171,
 282,
 282,
 281,
 282,
 282,
 156,
 282,
 213,
 213,
 162,
 282,
 173,
 282,
 282,
 282,
 156,
 225,
 156,
 242,
 156,
 75,
 282,
 206,
 109,
 212,
 282,
 282,
 282,
 211,
 256,
 156,
 282,
 282,
 282,
 225,
 281,
 282,
 282,
 81,
 282,
 225,
 203,
 282,
 235,
 282,
 221,
 282,
 108,
 226,
 175,
 256,
 282,
 156,
 282,
 282,
 282,
 282,
 282,
 256,
 108,
 282,
 175,
 282,
 272,
 224,
 282,
 282,
 225,
 282,
 173,
 256,
 224,
 282,
 273,
 221,
 282,
 282,
 282,
 282,
 277,
 176,
 282,
 149,
 282,
 220,
 132,
 112,
 282,
 282,
 282,
 282,
 282,
 282,
 114,
 255,
 87,
 282,
 282,
 282,
 282,
 282,
 114,
 282,
 282,
 282,
 211,
 149,
 282,
 282,
 130,
 130,
 92,
 282,
 129,
 281,
 282,
 276,
 203,
 117,
 282,
 282,
 282,
 282,
 177,
 101,
 282,
 177,
 282,
 94,
 282,
 282,
 282,
 282,
 273,
 282,
 111,
 275,
 282,
 282,
 282,
 282,
 282,
 282,
 282,
 282,
 282,
 282,
 219,
 198,
 65,
 282,
 106,
 204,
 254,
 282,
 224,
 172,
 282,
 282,
 282,
 282,
 281,
 74,
 274,
 282,
 282,
 282,
 112,
 124,
 114,
 281,
 282,
 114,
 118,
 124,
 80,
 224,
 282,
 282,
 89,
 282,
 282,
 161,
 215,
 282,
 170,
 255,
 124,
 234,
 166,
 226,
 106,
 147,
 282,
 26,
 281,
 282,
 162,
 176,
 220,
 214,
 268,
 167,
 282,
 275,
 282,
 218,
 114,
 217,
 220,
 282,
 282,
 282,
 218,
 282,
 282,
 282,
 225,
 282,
 216,
 282,
 279,
 101,
 282,
 88,
 229,
 282,
 282,
 175,
 277,
 282,
 282,
 118,
 282,
 282,
 114,
 118,
 282,
 275,
 218,
 282,
 282,
 160,
 282,
 282,
 109,
 232,
 267,
 282,
 104,
 282,
 282,
 223,
 282,
 229,
 114,
 166,
 177,
 282,
 282,
 282,
 253,
 74,
 201,
 95,
 282,
 282,
 282,
 102,
 282,
 121,
 281,
 282,
 282,
 282,
 282,
 282,
 186,
 115,
 282,
 197,
 282,
 230,
 258,
 282,
 282,
 26,
 104,
 282,
 282,
 174,
 109,
 79,
 276,
 216,
 282,
 282,
 282,
 282,
 204,
 276,
 275,
 282,
 191,
 167,
 220,
 282,
 282,
 282,
 282,
 282,
 231,
 269,
 282,
 282,
 176,
 94,
 282,
 203,
 282,
 282,
 282,
 282,
 117,
 282,
 35,
 104,
 89,
 282,
 81,
 88,
 224,
 282,
 202,
 192,
 282,
 165,
 265,
 197,
 282,
 279,
 282,
 190,
 227,
 282,
 190,
 228,
 174,
 89,
 176,
 231,
 282,
 282,
 282,
 114,
 105,
 203,
 282,
 282,
 281,
 282,
 267,
 282,
 114,
 118,
 282,
 282,
 108,
 282,
 91,
 282,
 282,
 282,
 167,
 281,
 282,
 282,
 222,
 137,
 263,
 274,
 282,
 282,
 273,
 204,
 282,
 232,
 133,
 282,
 201,
 251,
 265,
 282,
 265,
 282,
 282,
 282,
 153,
 254,
 282,
 282,
 118,
 254,
 282,
 282,
 124,
 282,
 282,
 228,
 282,
 282,
 257,
 266,
 240,
 207,
 214,
 281,
 282,
 119,
 282,
 282,
 282,
 141,
 101,
 282,
 282,
 217,
 159,
 282,
 265,
 282,
 157,
 122,
 282,
 282,
 282,
 282,
 282,
 282,
 105,
 118,
 282,
 91,
 245,
 275,
 282,
 94,
 282,
 282,
 122,
 276,
 282,
 282,
 282,
 108,
 282,
 37,
 277,
 282,
 282,
 160,
 282,
 192,
 227,
 105,
 282,
 282,
 76,
 282,
 282,
 108,
 282,
 159,
 255,
 282,
 220,
 282,
 282,
 140,
 76,
 162,
 282,
 123,
 281,
 172,
 97,
 164,
 282,
 278,
 149,
 282,
 282,
 121,
 282,
 108,
 282,
 282,
 230,
 146,
 282,
 121,
 282,
 282,
 250,
 282,
 282,
 282,
 282,
 180,
 127,
 149,
 282,
 162,
 219,
 74,
 273,
 221,
 230,
 268,
 224,
 129,
 280,
 192,
 74,
 224,
 208,
 282,
 146,
 215,
 282,
 230,
 280,
 203,
 145,
 282,
 151,
 180,
 255,
 282,
 265,
 277,
 223,
 282,
 282,
 275,
 183,
 167,
 124,
 135,
 172,
 166,
 282,
 138,
 282,
 282,
 282,
 282,
 273,
 282,
 128,
 120,
 282,
 163,
 120,
 282,
 282,
 282,
 282,
 281,
 180,
 282,
 282,
 282,
 282,
 281,
 199,
 253,
 282,
 278,
 233,
 129,
 169,
 282,
 255,
 282,
 146,
 103,
 261,
 282,
 215,
 282,
 282,
 282,
 282,
 74,
 230,
 185,
 127,
 282,
 282,
 99,
 273,
 282,
 282,
 159,
 237,
 254,
 276,
 282,
 72,
 95,
 282,
 122,
 233,
 282,
 230,
 282,
 238,
 145,
 282,
 281,
 282,
 67,
 282,
 234,
 282,
 282,
 113,
 250,
 282,
 282,
 282,
 107,
 172,
 224,
 282,
 282,
 282,
 282,
 100,
 282,
 75,
 148,
 282,
 264,
 147,
 113,
 85,
 196,
 282,
 273,
 215,
 269,
 282,
 233,
 145,
 220,
 282,
 277,
 282,
 231,
 207,
 282,
 282,
 159,
 124,
 282,
 156,
 282,
 281,
 260,
 282,
 192,
 163,
 269,
 282,
 281,
 282,
 282,
 190,
 129,
 149,
 282,
 199,
 101,
 220,
 282,
 282,
 275,
 282,
 268,
 225,
 282,
 125,
 282,
 128,
 107,
 279,
 247,
 282,
 282,
 282,
 282,
 282,
 131,
 282,
 282,
 282,
 170,
 280,
 277,
 179,
 180,
 282,
 282,
 171,
 281,
 281,
 282,
 282,
 230,
 282,
 158,
 282,
 282,
 271,
 233,
 282,
 172,
 77,
 79,
 282,
 282,
 238,
 238,
 79,
 282,
 104,
 282,
 42,
 282,
 278,
 282,
 210,
 282,
 130,
 282,
 222,
 282,
 282,
 129,
 282,
 123,
 76,
 269,
 282,
 281,
 152,
 269,
 149,
 281,
 271,
 273,
 176,
 282,
 282,
 277,
 176,
 281,
 282,
 282,
 23,
 166,
 282,
 175,
 282,
 282,
 282,
 282,
 282,
 282,
 173,
 219,
 256,
 277,
 251,
 282,
 166,
 277,
 282,
 234,
 219,
 282,
 282,
 282,
 231,
 204,
 184,
 190,
 282,
 225,
 282,
 253,
 282,
 185,
 282,
 282,
 255,
 120,
 281,
 230,
 282,
 94,
 121,
 282,
 124,
 282,
 281,
 282,
 145,
 282,
 282,
 282,
 282,
 282,
 49,
 282,
 282,
 67,
 154,
 282,
 282,
 282,
 166,
 132,
 275,
 172,
 184,
 282,
 126,
 257,
 77,
 282,
 282,
 282,
 67,
 107,
 111,
 282,
 282,
 282,
 279,
 282,
 282,
 215,
 282,
 187,
 123,
 282,
 224,
 268,
 221,
 282,
 ...]